Managed identity keyvault connection
vwt-data-platform/terraform pull request #243
Opened 2022-12-13 13:06 UTC by ArtiomMatiom

2022-12-13 14:11 UTC, JeffreyVWT requested changes

2022-12-13 14:11 UTC, JeffreyVWT commented on modules/azure/api_connectors/key_vault_managed_identity/main.tf
> +resource "azurerm_resource_group_template_deployment" "service_bus_managed_identity" {
servicebus!

2022-12-13 14:13 UTC, JeffreyVWT requested changes

2022-12-13 14:13 UTC, JeffreyVWT commented on modules/azure/api_connectors/key_vault_managed_identity/connection.json
> +          "alternativeParameterValues": {
Do you need this too ?

"parameterValueSet": {
          "name": "managedIdentityAuth",

2022-12-13 14:54 UTC, ArtiomMatiom commented on modules/azure/api_connectors/key_vault_managed_identity/connection.json
> +        "description": "Service Bus namespace"
changed to Keyvault Name for the connection target

2022-12-13 14:54 UTC, ArtiomMatiom commented on modules/azure/api_connectors/key_vault_managed_identity/main.tf
> +resource "azurerm_resource_group_template_deployment" "service_bus_managed_identity" {
renamed to key_vault_managed_identity

2022-12-14 12:45 UTC, JeffreyVWT commented on modules/azure/api_connectors/key_vault_managed_identity/connection.json
> +          "alternativeParameterValues": {
Ok :)

2022-12-14 12:45 UTC, JeffreyVWT requested changes

2022-12-14 12:45 UTC, JeffreyVWT commented on modules/azure/api_connectors/key_vault_managed_identity/connection.json
> +        "description": "Service Bus namespace"
I still see
```"description": "Service Bus namespace"```

2022-12-14 12:46 UTC, JeffreyVWT approved these changes

2022-12-15 07:46 UTC, merged